name: Sync Docker Images

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync images using image-syncer
        id: sync
        uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./sync-images.yaml
          version: latest
          proc: 6
        env:
          ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GCR_USERNAME: ${{ secrets.GCR_USERNAME }}
          GCR_PASSWORD: ${{ secrets.GCR_PASSWORD }}
        continue-on-error: true